# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Colflow < Formula
  desc "CLI for Dagster collection-flow pipelines: runs, assets, parquet inspection, asset scaffolding"
  homepage "https://github.com/CogappLabs/colflow-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.3/colflow_0.2.3_darwin_amd64.tar.gz"
      sha256 "43dbf1e40232a95a91af2f99dc1652c29167fcb8411995ba6f781cdf3f665ebd"

      define_method(:install) do
        bin.install "colflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.3/colflow_0.2.3_darwin_arm64.tar.gz"
      sha256 "ac80d9fcc3d660b31d004464eb8dac458fad4ef36ed7b918edce91e543929528"

      define_method(:install) do
        bin.install "colflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.3/colflow_0.2.3_linux_amd64.tar.gz"
      sha256 "f1045bcaec7f236b63939027e89d1a7d9ec460d5ef17f03f4dac062b03578756"
      define_method(:install) do
        bin.install "colflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.3/colflow_0.2.3_linux_arm64.tar.gz"
      sha256 "f2c9d87aebbf5a6e3f38399d89b5cb69e81761f7a1879e8d987bf4ec11093579"
      define_method(:install) do
        bin.install "colflow"
      end
    end
  end

  test do
    system "#{bin}/colflow", "--version"
  end
end
