# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Colflow < Formula
  desc "CLI for Dagster collection-flow pipelines: runs, assets, parquet inspection, asset scaffolding"
  homepage "https://github.com/CogappLabs/colflow-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.1.0/colflow_0.1.0_darwin_amd64.tar.gz"
      sha256 "9862bd71ae6a7d038b040b39eaac6cd6e11b8c2598b1c4518ec593dc82aa6385"

      define_method(:install) do
        bin.install "colflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.1.0/colflow_0.1.0_darwin_arm64.tar.gz"
      sha256 "f5a7d32003dd28e3d50120a4ab2c90e726ac10a35f148b87e5b7e776ab67e15e"

      define_method(:install) do
        bin.install "colflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.1.0/colflow_0.1.0_linux_amd64.tar.gz"
      sha256 "beb2883ea15f66c69b6f012d9e0538b4d1cd39c235859060cfe3c00c205d1e40"
      define_method(:install) do
        bin.install "colflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.1.0/colflow_0.1.0_linux_arm64.tar.gz"
      sha256 "264dbebe10d657794a1cbd2361d72d3531455f9956d06336b69d5b79fe91f5b5"
      define_method(:install) do
        bin.install "colflow"
      end
    end
  end

  test do
    system "#{bin}/colflow", "--version"
  end
end
