# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Colflow < Formula
  desc "CLI for Dagster collection-flow pipelines: runs, assets, parquet inspection, asset scaffolding"
  homepage "https://github.com/CogappLabs/colflow-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.2/colflow_0.2.2_darwin_amd64.tar.gz"
      sha256 "d921fb65c1f5c550da1f5aa85dcf030784399ba31a864ca1bdf1d1c820342fe9"

      define_method(:install) do
        bin.install "colflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.2/colflow_0.2.2_darwin_arm64.tar.gz"
      sha256 "91984b660859cd5b153528e94cb3c63824fb0f42c7e7055f85028575e9eccfe4"

      define_method(:install) do
        bin.install "colflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.2/colflow_0.2.2_linux_amd64.tar.gz"
      sha256 "26b002a53b7b5d45a7c63fb7e3833f0250d155f7f70c75151ef7f1c26b491f3e"
      define_method(:install) do
        bin.install "colflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CogappLabs/colflow-cli/releases/download/v0.2.2/colflow_0.2.2_linux_arm64.tar.gz"
      sha256 "422bac3519d5e68e5e353600c9cde80c16d978677ee401e012d9704b40e2a6d5"
      define_method(:install) do
        bin.install "colflow"
      end
    end
  end

  test do
    system "#{bin}/colflow", "--version"
  end
end
